version: '3.7'
services:
    mariadb:
        image: mariadb:10.2.17
        volumes:
            - ./etc/dev/mysql:/var/lib/mysql:rw
            - ./etc/dev/mysql:/app
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=tiburones
